/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_8410();
// int strtol(const char *nptr, char **endptr, int base);
// int printf(const char *format, ...);
// void *memcpy(void *dest, const void *src, size_t n);
// int IO_getc(_IO_FILE *fp);
// int gettimeofday(struct timeval *tv, __timezone_ptr_t tz);
// void *malloc(size_t size);
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
int j___gmon_start__();
// int _gmon_start__(void); weak
// void *memset(void *s, int c, size_t n);
// int sprintf(char *s, const char *format, ...);
// void abort(void);
int __cdecl main(int argc, const char **argv, const char **envp);
void __noreturn start(void (*)(void), int, int, int, ...); // idb
int call_gmon_start();
void *deregister_tm_clones();
__int64 register_tm_clones();
void *_do_global_dtors_aux();
int __fastcall frame_dummy(int a1, int a2, int a3, int a4);
int __fastcall bin2hex(int s, unsigned __int8 *a2, int a3);
void *__fastcall abin2hex(unsigned __int8 *a1, int a2);
bool __fastcall hex2bin(int, unsigned __int8 *, int); // idb
int __fastcall blake2b_hash(_DWORD *, char *); // idb
__int64 *__fastcall blake2b_compress(int, int); // idb
__int64 *__fastcall blake2b_update(__int64 *result, char *, int); // idb
int __fastcall blake2b_init(int, int, char *, unsigned int); // idb
__int64 *__fastcall blake2b_final(int, int); // idb
int __fastcall init(int a1, int a2, int a3);
int _libc_csu_fini(); // weak
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_9518; // weak
_UNKNOWN unk_95D0; // weak
_UNKNOWN unk_9610; // weak
int _JCR_LIST__ = 0; // weak
_UNKNOWN _TMC_END__; // weak
int stdin; // weak
char completed_8605; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00008404) --------------------------------------------------------
int init_proc()
{
  return call_gmon_start();
}

//----- (00008410) --------------------------------------------------------
void sub_8410()
{
  JUMPOUT(0);
}
// 841C: control flows out of bounds to 0

//----- (00008478) --------------------------------------------------------
// attributes: thunk
int j___gmon_start__()
{
  return _gmon_start__();
}
// 847C: using guessed type int _gmon_start__(void);

//----- (000084AC) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int v3; // r4
  int v4; // r3
  int v5; // r1
  int v6; // r2
  char v8[161]; // [sp+3Fh] [bp-A1h] BYREF
  struct timeval v9; // [sp+E0h] [bp+0h] BYREF
  struct timeval v10; // [sp+E8h] [bp+8h] BYREF
  unsigned __int8 v11[164]; // [sp+F0h] [bp+10h] BYREF
  char v12[164]; // [sp+194h] [bp+B4h] BYREF

  strcpy(
    v12,
    "002800270026002500240023002200210020001f001e001d001c001b001a0019630999000016001500140013001200110010000f000e000d000c"
    "000b000a000900080007000600050004000300020001");
  memcpy(v11, v12, 0xA1u);
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x80) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x84) = 0;
  v3 = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x88) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x8C) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x90) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x94) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x98) = 0;
  *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x9C) = 0;
  memset((void *)((unsigned int)v8 & 0xFFFFFFC0), 0, 0x50u);
  hex2bin((unsigned int)v8 & 0xFFFFFFC0, v11, 160);
  *(_DWORD *)((unsigned int)v8 & 0xFFFFFFC0) += 5;
  gettimeofday(&v9, 0);
  do
  {
    *(_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 0x20) = ++v3;
    blake2b_hash((_DWORD *)(((unsigned int)v8 & 0xFFFFFFC0) + 128), (char *)((unsigned int)v8 & 0xFFFFFFC0));
  }
  while ( v3 != 1000000 );
  gettimeofday(&v10, 0);
  v4 = v10.tv_usec - v9.tv_usec;
  LOWORD(v5) = 16960;
  v6 = v10.tv_sec - v9.tv_sec;
  if ( v10.tv_usec - v9.tv_usec < 0 )
  {
    v4 += 1000000;
    --v6;
  }
  HIWORD(v5) = 15;
  printf("%d %d:%d\n", v5, v6, v4);
  IO_getc((_IO_FILE *)stdin);
  return 0;
}
// 11768: using guessed type int stdin;

//----- (00008594) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    (char **)va,
    (void (*)(void))init,
    (void (*)(void))_libc_csu_fini,
    a1,
    va);
  abort();
}
// 85A0: positive sp value 4 has been found
// 85B6: variable 'v4' is possibly undefined
// 93D8: using guessed type int init();
// 941C: using guessed type int _libc_csu_fini();

//----- (000085CC) --------------------------------------------------------
int call_gmon_start()
{
  int result; // r0

  if ( &__gmon_start__ )
    return j___gmon_start__();
  return result;
}

//----- (000085E4) --------------------------------------------------------
void *deregister_tm_clones()
{
  return &_TMC_END__;
}

//----- (00008608) --------------------------------------------------------
__int64 register_tm_clones()
{
  __int64 result; // r0

  LODWORD(result) = &_TMC_END__;
  HIDWORD(result) = 0;
  return result;
}

//----- (00008634) --------------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // r0

  if ( !completed_8605 )
  {
    result = deregister_tm_clones();
    completed_8605 = 1;
  }
  return result;
}
// 1176C: using guessed type char completed_8605;

//----- (0000864C) --------------------------------------------------------
int __fastcall frame_dummy(int a1, int a2, int a3, int a4)
{
  return register_tm_clones(&_JCR_LIST__, a2, a3, a4);
}
// 8608: using guessed type int __fastcall register_tm_clones(_DWORD, _DWORD, _DWORD, _DWORD);
// 1162C: using guessed type int _JCR_LIST__;

//----- (0000866C) --------------------------------------------------------
int __fastcall bin2hex(int s, unsigned __int8 *a2, int a3)
{
  unsigned __int8 *v3; // r4
  int v4; // r5
  unsigned __int8 *v5; // r6
  int v6; // t1
  char *v7; // r0

  if ( a3 )
  {
    v3 = a2;
    v4 = s;
    v5 = &a2[a3];
    do
    {
      v6 = *v3++;
      v7 = (char *)v4;
      v4 += 2;
      s = sprintf(v7, "%02x", v6);
    }
    while ( v3 != v5 );
  }
  return s;
}

//----- (00008690) --------------------------------------------------------
void *__fastcall abin2hex(unsigned __int8 *a1, int a2)
{
  void *v4; // r0
  void *v5; // r5

  v4 = malloc(2 * a2 + 1);
  v5 = v4;
  if ( v4 )
    bin2hex((int)v4, a1, a2);
  return v5;
}

//----- (000086B0) --------------------------------------------------------
bool __fastcall hex2bin(int a1, unsigned __int8 *a2, int a3)
{
  int v3; // r3
  int v4; // r5
  unsigned __int8 v5; // r6
  unsigned __int8 *v6; // r4
  int v7; // r7
  char v8; // r0
  char *v9; // r3
  char v11[4]; // [sp+0h] [bp-20h] BYREF
  char *endptr; // [sp+4h] [bp-1Ch] BYREF

  v3 = *a2;
  v4 = a3;
  v11[2] = 0;
  if ( !v3 )
    return a3 == 0;
  if ( !a3 )
    return 1;
  v5 = a2[1];
  if ( v5 )
  {
    v6 = a2;
    v7 = a1 - 1;
    while ( 1 )
    {
      v11[0] = v3;
      v11[1] = v5;
      --v4;
      v8 = strtol(v11, &endptr, 16);
      v9 = endptr;
      *(_BYTE *)++v7 = v8;
      if ( *v9 )
      {
        printf("hex2bin failed on '%s'", v11);
        return 0;
      }
      v3 = v6[2];
      v6 += 2;
      if ( !v3 )
        return v4 == 0;
      if ( !v4 )
        return 1;
      v5 = v6[1];
      if ( !v5 )
        goto LABEL_11;
    }
  }
  else
  {
LABEL_11:
    printf("hex2bin str truncated");
    return 0;
  }
}

//----- (00008734) --------------------------------------------------------
int __fastcall blake2b_hash(_DWORD *a1, char *a2)
{
  int v4; // r1
  int v5; // r2
  int v6; // r3
  int result; // r0
  int v8; // r1
  int v9; // r2
  int v10; // r3
  char v11[289]; // [sp+3Fh] [bp-121h] BYREF

  blake2b_init((unsigned int)v11 & 0xFFFFFFC0, 32, 0, 0);
  blake2b_update((__int64 *)((unsigned int)v11 & 0xFFFFFFC0), a2, 80);
  blake2b_final((unsigned int)v11 & 0xFFFFFFC0, ((unsigned int)v11 & 0xFFFFFFC0) + 256);
  v4 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x104);
  v5 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x108);
  v6 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x10C);
  *a1 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x100);
  a1[1] = v4;
  a1[2] = v5;
  a1[3] = v6;
  result = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x110);
  v8 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x114);
  v9 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x118);
  v10 = *(_DWORD *)(((unsigned int)v11 & 0xFFFFFFC0) + 0x11C);
  a1[4] = result;
  a1[5] = v8;
  a1[6] = v9;
  a1[7] = v10;
  return result;
}

//----- (00008784) --------------------------------------------------------
__int64 *__fastcall blake2b_compress(int a1, int a2)
{
  __int64 *v2; // r7
  int v3; // r6
  char **v4; // r12
  _QWORD *v5; // r9
  int v6; // r8
  __int64 v7; // r0
  __int64 v8; // t1
  __int64 v9; // t1
  __int64 v10; // r6
  unsigned __int8 *v11; // r6
  char *v12; // r7
  int v13; // r2
  int v14; // r0
  int v15; // r10
  int v16; // r5
  int v17; // r1
  __int64 v18; // r2
  unsigned __int8 *v19; // r12
  __int64 v20; // r6
  __int64 v21; // r8
  signed __int64 v22; // r0
  unsigned __int64 v23; // r4
  unsigned __int64 v24; // r8
  unsigned __int64 v25; // r6
  signed __int64 v26; // r4
  __int64 v27; // r6
  __int64 v28; // r2
  unsigned __int64 v29; // r10
  __int64 v30; // r4
  __int64 v31; // r0
  __int64 v32; // r2
  __int64 v33; // r4
  __int64 v34; // r10
  __int64 v35; // r4
  __int64 v36; // r2
  __int64 *result; // r0
  __int64 *v38; // r1
  _QWORD *v39; // r2
  __int64 v40; // r6
  int v41; // r3
  __int64 i; // r8
  __int64 v43; // t1
  __int64 v44; // t1
  __int64 v45; // [sp+8h] [bp-190h]
  __int64 v46; // [sp+10h] [bp-188h]
  unsigned __int64 v47; // [sp+10h] [bp-188h]
  __int64 v48; // [sp+10h] [bp-188h]
  __int64 v49; // [sp+10h] [bp-188h]
  int v50; // [sp+18h] [bp-180h]
  __int64 v51; // [sp+18h] [bp-180h]
  unsigned __int64 v52; // [sp+18h] [bp-180h]
  __int64 v53; // [sp+18h] [bp-180h]
  __int64 v54; // [sp+18h] [bp-180h]
  int v55; // [sp+20h] [bp-178h]
  __int64 v56; // [sp+20h] [bp-178h]
  __int64 v57; // [sp+20h] [bp-178h]
  __int64 v58; // [sp+20h] [bp-178h]
  unsigned __int64 v59; // [sp+20h] [bp-178h]
  __int64 v60; // [sp+28h] [bp-170h]
  __int64 v61; // [sp+28h] [bp-170h]
  unsigned __int64 v62; // [sp+28h] [bp-170h]
  unsigned __int64 v63; // [sp+30h] [bp-168h]
  int v64; // [sp+38h] [bp-160h]
  __int64 v65; // [sp+38h] [bp-160h]
  __int64 v66; // [sp+40h] [bp-158h]
  unsigned __int64 v67; // [sp+40h] [bp-158h]
  __int64 v68; // [sp+40h] [bp-158h]
  __int64 v69; // [sp+48h] [bp-150h]
  unsigned __int64 v70; // [sp+48h] [bp-150h]
  unsigned __int64 v71; // [sp+48h] [bp-150h]
  __int64 v72; // [sp+50h] [bp-148h]
  __int64 v73; // [sp+58h] [bp-140h]
  __int64 v74; // [sp+60h] [bp-138h]
  __int64 v75; // [sp+68h] [bp-130h]
  unsigned __int64 v76; // [sp+68h] [bp-130h]
  __int64 v77; // [sp+68h] [bp-130h]
  __int64 v78; // [sp+70h] [bp-128h]
  __int64 v79; // [sp+70h] [bp-128h]
  unsigned __int64 v80; // [sp+78h] [bp-120h]
  unsigned __int64 v81; // [sp+78h] [bp-120h]
  __int64 v83; // [sp+80h] [bp-118h]
  __int64 v84; // [sp+88h] [bp-110h]
  __int64 v85; // [sp+90h] [bp-108h]
  unsigned __int64 v86; // [sp+A0h] [bp-F8h]
  __int64 v87; // [sp+A8h] [bp-F0h]
  __int64 v88; // [sp+B0h] [bp-E8h]
  unsigned __int64 v89; // [sp+C0h] [bp-D8h]
  unsigned __int64 v90; // [sp+C8h] [bp-D0h]
  unsigned __int64 v91; // [sp+D0h] [bp-C8h]
  unsigned __int64 v92; // [sp+D8h] [bp-C0h]
  __int64 v93; // [sp+E0h] [bp-B8h]
  unsigned __int64 v94; // [sp+E8h] [bp-B0h]
  unsigned __int64 v95; // [sp+F0h] [bp-A8h]
  unsigned __int64 v96; // [sp+F8h] [bp-A0h]
  __int64 v97; // [sp+100h] [bp-98h]
  unsigned __int64 v98; // [sp+108h] [bp-90h]
  unsigned __int64 v99; // [sp+110h] [bp-88h]
  __int64 v100; // [sp+118h] [bp-80h]
  unsigned __int64 v101; // [sp+120h] [bp-78h]
  __int64 v102; // [sp+128h] [bp-70h]
  __int64 v103; // [sp+130h] [bp-68h]
  __int64 v104; // [sp+138h] [bp-60h]
  unsigned __int64 v105; // [sp+140h] [bp-58h]
  unsigned __int64 v106; // [sp+148h] [bp-50h]
  __int64 v107; // [sp+150h] [bp-48h]
  char *v108; // [sp+158h] [bp-40h] BYREF
  int v109; // [sp+15Ch] [bp-3Ch]
  __int64 v110; // [sp+160h] [bp-38h] BYREF
  __int64 v111; // [sp+168h] [bp-30h]
  __int64 v112; // [sp+170h] [bp-28h]
  __int64 v113; // [sp+178h] [bp-20h]
  __int64 v114; // [sp+180h] [bp-18h]
  __int64 v115; // [sp+188h] [bp-10h]
  __int64 v116; // [sp+190h] [bp-8h]
  __int64 v117; // [sp+198h] [bp+0h] BYREF
  __int64 v118; // [sp+1A0h] [bp+8h] BYREF
  __int64 v119; // [sp+1A8h] [bp+10h]
  __int64 v120; // [sp+1B0h] [bp+18h]
  __int64 v121; // [sp+1B8h] [bp+20h]
  __int64 v122; // [sp+1C0h] [bp+28h]
  __int64 v123; // [sp+1C8h] [bp+30h]
  __int64 v124; // [sp+1D0h] [bp+38h]
  _QWORD v125[16]; // [sp+1D8h] [bp+40h] BYREF
  char v126; // [sp+258h] [bp+C0h] BYREF
  char dest[192]; // [sp+260h] [bp+C8h] BYREF
  char v128; // [sp+320h] [bp+188h] BYREF

  v109 = a1;
  v2 = &v117;
  v3 = 8;
  memcpy(dest, &unk_9518, sizeof(dest));
  v4 = &v108;
  v5 = &unk_95D0;
  v6 = v109 + 120;
  do
  {
    v8 = *(_QWORD *)(v6 + 8);
    v6 += 8;
    v7 = v8;
    --v3;
    v9 = v5[1];
    ++v5;
    *((_QWORD *)v4 + 1) = v7;
    v4 += 2;
    v2[1] = v9;
    ++v2;
  }
  while ( v3 );
  v10 = *(_QWORD *)(v109 + 200);
  v122 ^= *(_QWORD *)(v109 + 192);
  v84 = v122;
  v85 = v10 ^ v123;
  v123 ^= v10;
  if ( a2 )
  {
    v83 = ~v124;
    v124 = ~v124;
  }
  else
  {
    v83 = v124;
  }
  v11 = (unsigned __int8 *)v109;
  v12 = (char *)v125;
  do
  {
    v13 = *v11;
    v14 = v11[2] << 16;
    v15 = v11[1] << 8;
    v55 = v11[5];
    v64 = v11[3] << 24;
    v16 = v11[4];
    v50 = v11[6];
    v17 = v11[7];
    v11 += 8;
    LODWORD(v18) = v13 ^ v15 ^ v14 ^ v64;
    HIDWORD(v18) = v16 ^ (v55 << 8) ^ (v50 << 16) ^ (v17 << 24);
    *((_QWORD *)v12 + 1) = v18;
    v12 += 8;
  }
  while ( v12 != &v126 );
  v69 = v111;
  v78 = v110;
  v74 = v114;
  v108 = &v128;
  v66 = v120;
  v46 = v118;
  v19 = (unsigned __int8 *)dest;
  v65 = v115;
  v51 = v112;
  v72 = v116;
  v56 = v121;
  v20 = v119;
  v60 = v113;
  v73 = v117;
  v63 = v125[0];
  do
  {
    v21 = v125[v19[2] + 1] + v65 + v69;
    v70 = v20 + __PAIR64__((unsigned int)v85 ^ (unsigned int)v21, HIDWORD(v85) ^ HIDWORD(v21));
    v89 = __PAIR64__(
            ((unsigned int)((v70 ^ v65) >> 32) >> 24) | (((unsigned int)v70 ^ (unsigned int)v65) << 8),
            (__int64)(v70 ^ v65) >> 24);
    v75 = v125[v19[6] + 1] + v73 + v60;
    v61 = v125[v19[4] + 1] + v72 + v51;
    v52 = v125[v19[3] + 1]
        + v21
        + __PAIR64__(
            ((unsigned int)((v70 ^ v65) >> 32) >> 24) | (((unsigned int)v70 ^ (unsigned int)v65) << 8),
            (__int64)(v70 ^ v65) >> 24);
    v96 = __PAIR64__((unsigned int)v63 ^ (unsigned int)v75, HIDWORD(v63) ^ HIDWORD(v75));
    v80 = v56 + __PAIR64__((unsigned int)v63 ^ (unsigned int)v75, HIDWORD(v63) ^ HIDWORD(v75));
    v79 = v74 + v125[*v19 + 1] + v78;
    HIDWORD(v90) = ((unsigned int)((v52 ^ __PAIR64__((unsigned int)v85 ^ (unsigned int)v21, HIDWORD(v85) ^ HIDWORD(v21))) >> 32) >> 16) | (((unsigned int)v52 ^ HIDWORD(v85) ^ HIDWORD(v21)) << 16);
    v92 = __PAIR64__((unsigned int)v83 ^ (unsigned int)v61, HIDWORD(v83) ^ HIDWORD(v61));
    LODWORD(v90) = (__int64)(v52 ^ __PAIR64__((unsigned int)v85 ^ (unsigned int)v21, HIDWORD(v85) ^ HIDWORD(v21))) >> 16;
    v67 = v66 + __PAIR64__((unsigned int)v83 ^ (unsigned int)v61, HIDWORD(v83) ^ HIDWORD(v61));
    v22 = (v56 + __PAIR64__((unsigned int)v63 ^ (unsigned int)v75, HIDWORD(v63) ^ HIDWORD(v75))) ^ v73;
    HIDWORD(v97) = HIBYTE(HIDWORD(v22)) | ((_DWORD)v22 << 8);
    v47 = v46 + __PAIR64__((unsigned int)v84 ^ (unsigned int)v79, HIDWORD(v84) ^ HIDWORD(v79));
    v71 = v90 + v20 + __PAIR64__((unsigned int)v85 ^ (unsigned int)v21, HIDWORD(v85) ^ HIDWORD(v21));
    LODWORD(v97) = v22 >> 24;
    HIDWORD(v93) = ((unsigned int)((v67 ^ v72) >> 32) >> 24) | (((unsigned int)v67 ^ (unsigned int)v72) << 8);
    v57 = v75 + v125[v19[7] + 1];
    v76 = v52 + v125[v19[10] + 1];
    HIDWORD(v91) = (__int64)(v71 ^ v89) >> 31;
    LODWORD(v91) = (2 * (v71 ^ v89)) | ((unsigned int)((v71 ^ v89) >> 32) >> 31);
    LODWORD(v93) = (__int64)(v67 ^ v72) >> 24;
    v53 = v57 + v97;
    v58 = v125[v19[5] + 1] + v61 + v93;
    v86 = __PAIR64__(
            ((unsigned int)((v47 ^ v74) >> 32) >> 24) | (((unsigned int)v47 ^ (unsigned int)v74) << 8),
            (__int64)(v47 ^ v74) >> 24);
    v23 = v125[v19[1] + 1]
        + v79
        + __PAIR64__(
            ((unsigned int)((v47 ^ v74) >> 32) >> 24) | (((unsigned int)v47 ^ (unsigned int)v74) << 8),
            (__int64)(v47 ^ v74) >> 24);
    HIDWORD(v98) = ((unsigned int)((v53 ^ v96) >> 32) >> 16) | (((unsigned int)v53 ^ (unsigned int)v96) << 16);
    LODWORD(v98) = (__int64)(v53 ^ v96) >> 16;
    v24 = v125[v19[8] + 1] + v23 + v91;
    v94 = __PAIR64__(
            ((unsigned int)((v58 ^ v92) >> 32) >> 16) | (((unsigned int)v58 ^ (unsigned int)v92) << 16),
            (__int64)(v58 ^ v92) >> 16);
    LODWORD(v100) = (v24 ^ v98) >> 32;
    HIDWORD(v100) = v24 ^ v98;
    v25 = __PAIR64__(
            ((unsigned int)((v58 ^ v92) >> 32) >> 16) | (((unsigned int)v58 ^ (unsigned int)v92) << 16),
            (__int64)(v58 ^ v92) >> 16)
        + v67;
    v68 = v100
        + __PAIR64__(
            ((unsigned int)((v58 ^ v92) >> 32) >> 16) | (((unsigned int)v58 ^ (unsigned int)v92) << 16),
            (__int64)(v58 ^ v92) >> 16)
        + v67;
    v26 = v23 ^ __PAIR64__((unsigned int)v84 ^ (unsigned int)v79, HIDWORD(v84) ^ HIDWORD(v79));
    HIDWORD(v87) = HIWORD(HIDWORD(v26)) | ((_DWORD)v26 << 16);
    v27 = v25 ^ v93;
    LODWORD(v87) = v26 >> 16;
    HIDWORD(v101) = ((unsigned int)((v68 ^ v91) >> 32) >> 24) | (((unsigned int)v68 ^ (unsigned int)v91) << 8);
    v48 = v87 + v47;
    LODWORD(v101) = (__int64)(v68 ^ v91) >> 24;
    HIDWORD(v95) = v27 >> 31;
    v28 = v125[v19[9] + 1] + v24 + v101;
    v78 = v28;
    HIDWORD(v28) ^= v24 ^ (unsigned int)v98;
    LODWORD(v28) = v28 ^ v100;
    LODWORD(v95) = (2 * v27) | (HIDWORD(v27) >> 31);
    v63 = __PAIR64__(HIWORD(HIDWORD(v28)) | ((_DWORD)v28 << 16), v28 >> 16);
    v29 = v76 + v95;
    v30 = (v98 + v80) ^ v97;
    LODWORD(v102) = ((v76 + v95) ^ v87) >> 32;
    HIDWORD(v102) = (v76 + v95) ^ v87;
    HIDWORD(v99) = v30 >> 31;
    v45 = v125[v19[14] + 1];
    HIDWORD(v88) = (__int64)(v48 ^ v86) >> 31;
    v66 = __PAIR64__(HIWORD(HIDWORD(v28)) | ((_DWORD)v28 << 16), v28 >> 16) + v68;
    v77 = v102 + v98 + v80;
    v62 = v29 + v125[v19[11] + 1];
    LODWORD(v99) = (2 * v30) | (HIDWORD(v30) >> 31);
    LODWORD(v88) = (2 * (v48 ^ v86)) | ((unsigned int)((v48 ^ v86) >> 32) >> 31);
    HIDWORD(v24) = v19[13];
    LODWORD(v24) = v19[15];
    v59 = v125[v19[12] + 1] + v58 + v99;
    v19 += 16;
    v54 = v45 + v53 + v88;
    LODWORD(v104) = (v59 ^ v90) >> 32;
    HIDWORD(v104) = v59 ^ v90;
    LODWORD(v106) = (v54 ^ v94) >> 32;
    HIDWORD(v106) = v54 ^ v94;
    v49 = v104 + v48;
    v81 = v106 + v71;
    v31 = (v106 + v71) ^ v88;
    HIDWORD(v103) = ((unsigned int)((v77 ^ v95) >> 32) >> 24) | (((unsigned int)v77 ^ (unsigned int)v95) << 8);
    HIDWORD(v65) = (__int64)(v66 ^ v101) >> 31;
    LODWORD(v103) = (__int64)(v77 ^ v95) >> 24;
    HIDWORD(v107) = HIBYTE(HIDWORD(v31)) | ((_DWORD)v31 << 8);
    HIDWORD(v105) = ((unsigned int)((v49 ^ v99) >> 32) >> 24) | (((unsigned int)v49 ^ (unsigned int)v99) << 8);
    LODWORD(v65) = (2 * (v66 ^ v101)) | ((unsigned int)((v66 ^ v101) >> 32) >> 31);
    v69 = v62 + v103;
    LODWORD(v105) = (__int64)(v49 ^ v99) >> 24;
    v32 = (v62 + v103) ^ v102;
    LODWORD(v107) = v31 >> 24;
    HIDWORD(v84) = HIWORD(HIDWORD(v32)) | ((_DWORD)v32 << 16);
    LODWORD(v84) = v32 >> 16;
    v33 = v125[HIDWORD(v24) + 1] + v59 + v105;
    v34 = v125[(int)v24 + 1] + v54 + v107;
    v51 = v33;
    HIDWORD(v33) ^= v59 ^ (unsigned int)v90;
    LODWORD(v33) = v33 ^ v104;
    v60 = v34;
    HIDWORD(v83) = ((unsigned int)((v34 ^ v106) >> 32) >> 16) | (((unsigned int)v34 ^ (unsigned int)v106) << 16);
    HIDWORD(v85) = HIWORD(HIDWORD(v33)) | ((_DWORD)v33 << 16);
    LODWORD(v85) = v33 >> 16;
    LODWORD(v83) = (__int64)(v34 ^ v106) >> 16;
    v56 = v84 + v77;
    v46 = v85 + v49;
    v20 = v83 + v81;
    v35 = (v84 + v77) ^ v103;
    HIDWORD(v72) = v35 >> 31;
    v36 = (v83 + v81) ^ v107;
    v73 = (2 * (v46 ^ v105)) | ((unsigned int)((v46 ^ v105) >> 32) >> 31);
    LODWORD(v72) = (2 * v35) | (HIDWORD(v35) >> 31);
    HIDWORD(v74) = v36 >> 31;
    LODWORD(v74) = (2 * v36) | (HIDWORD(v36) >> 31);
  }
  while ( v19 != (unsigned __int8 *)v108 );
  result = &v110;
  v110 = v78;
  v38 = &v118;
  v125[0] = v63;
  v120 = v66;
  v115 = v65;
  v111 = v69;
  v122 = v84;
  v121 = v84 + v77;
  v116 = v72;
  v112 = v51;
  v123 = v85;
  v118 = v46;
  v117 = (2 * (v46 ^ v105)) | ((unsigned int)((v46 ^ v105) >> 32) >> 31);
  v113 = v34;
  v124 = v83;
  v119 = v83 + v81;
  v39 = (_QWORD *)(v109 + 128);
  v40 = v78;
  v41 = 8;
  v114 = v74;
  for ( i = v46; ; i = v44 )
  {
    --v41;
    *v39++ ^= v40 ^ i;
    if ( !v41 )
      break;
    v43 = result[1];
    ++result;
    v40 = v43;
    v44 = v38[1];
    ++v38;
  }
  return result;
}

//----- (00009238) --------------------------------------------------------
__int64 *__fastcall blake2b_update(__int64 *result, char *a2, int a3)
{
  __int64 *v3; // r8
  int v4; // r3
  char *v5; // r9
  char *v6; // r10
  char v7; // t1
  bool v8; // zf
  int v9; // r2
  unsigned __int64 v10; // r4
  char v11; // t1

  v3 = result;
  if ( a3 )
  {
    v4 = *((_DWORD *)result + 52);
    v5 = a2;
    v6 = &a2[a3];
    do
    {
      while ( 1 )
      {
        v8 = v4 == 128;
        v9 = v4++;
        if ( v8 )
          break;
        v7 = *v5++;
        *((_DWORD *)v3 + 52) = v4;
        *((_BYTE *)v3 + v9) = v7;
        if ( v5 == v6 )
          return result;
      }
      v10 = v3[24] + 128;
      v3[24] = v10;
      if ( v10 <= 0x7F )
        ++v3[25];
      result = blake2b_compress((int)v3, 0);
      *((_DWORD *)v3 + 52) = 0;
      v4 = 1;
      v11 = *v5++;
      *((_DWORD *)v3 + 52) = 1;
      *(_BYTE *)v3 = v11;
    }
    while ( v5 != v6 );
  }
  return result;
}

//----- (000092B8) --------------------------------------------------------
int __fastcall blake2b_init(int a1, int a2, char *a3, unsigned int a4)
{
  _QWORD *v5; // r0
  int v6; // r6
  __int64 v7; // t1
  __int64 v8; // r4
  unsigned int v9; // r9

  if ( (unsigned int)(a2 - 1) > 0x3F || a4 > 0x40 )
    return -1;
  v5 = &unk_95D0;
  v6 = a1 + 120;
  do
  {
    v7 = v5[1];
    ++v5;
    *(_QWORD *)(v6 + 8) = v7;
    v6 += 8;
  }
  while ( v5 != (_QWORD *)&unk_9610 );
  v8 = *(_QWORD *)(a1 + 128);
  v9 = a4;
  *(_DWORD *)(a1 + 212) = a2;
  *(_QWORD *)(a1 + 128) = v8 ^ a2 ^ 0x1010000 ^ (a4 << 8);
  *(_DWORD *)(a1 + 208) = 0;
  *(_QWORD *)(a1 + 192) = 0LL;
  *(_QWORD *)(a1 + 200) = 0LL;
  do
    *(_BYTE *)(a1 + v9++) = 0;
  while ( v9 != 128 );
  if ( a4 )
  {
    blake2b_update((__int64 *)a1, a3, a4);
    *(_DWORD *)(a1 + 208) = 128;
  }
  return 0;
}

//----- (00009344) --------------------------------------------------------
__int64 *__fastcall blake2b_final(int a1, int a2)
{
  unsigned int v4; // r1
  unsigned __int64 v5; // r4
  __int64 *result; // r0
  unsigned int v7; // r3
  char v8; // r2
  int v9; // r1
  unsigned int v10; // r4

  v4 = *(_DWORD *)(a1 + 208);
  v5 = *(_QWORD *)(a1 + 192) + v4;
  *(_QWORD *)(a1 + 192) = v5;
  if ( v5 < v4 )
    ++*(_QWORD *)(a1 + 200);
  if ( v4 <= 0x7F )
  {
    do
      *(_BYTE *)(a1 + v4++) = 0;
    while ( v4 != 128 );
    *(_DWORD *)(a1 + 208) = 128;
  }
  result = blake2b_compress(a1, 1);
  if ( *(_DWORD *)(a1 + 212) )
  {
    v7 = 0;
    do
    {
      v8 = 8 * (v7 & 7);
      v9 = (v7 >> 3) + 16;
      v10 = *(_DWORD *)(a1 + 8 * v9 + 4);
      result = (__int64 *)(v10 << (32 - v8));
      *(_BYTE *)(a2 + v7++) = (*(_DWORD *)(a1 + 8 * v9) >> v8) | (unsigned __int8)result | (v10 >> (v8 - 32));
    }
    while ( *(_DWORD *)(a1 + 212) > v7 );
  }
  return result;
}

//----- (000093D8) --------------------------------------------------------
int __fastcall init(int a1, int a2, int a3)
{
  unsigned int v6; // r5
  int i; // r4
  int (__fastcall *v8)(int, int, int, int); // t1
  int result; // r0

  init_proc();
  v6 = 0x11620u;
  for ( i = 0; i != 1; ++i )
  {
    v8 = *(int (__fastcall **)(int, int, int, int))(v6 + 4);
    v6 += 4;
    result = v8(a1, a2, a3, (int)v8);
  }
  return result;
}
// 8230: using guessed type Elf32_Sym;

//----- (00009420) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=43 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
