int sub_3DD54(int* param0, int param1, uint32_t* param2) {
    gvar_99EE20 = *(uint32_t*)param1;
    int v0 = 0;
    do {
        sub_3DEC0(param0, param1, &v0, param2);
    }
    while(param0 == SOCK_STREAM);
    return (int)param0 >= 0 ? ((int*)((int)(int*)((int)param0 >>> 30) & SOCK_STREAM) ? SOCK_STREAM: (int*)((int)(int*)((int)param0 >>> 29) & SOCK_STREAM) ? 2: (int*)((int)(int*)((int)param0 >>> 28) & SOCK_STREAM) ? 3: (int*)((int)(int*)((int)param0 >>> 27) & SOCK_STREAM) ? 4: (int*)((int)(int*)((int)param0 >>> 26) & SOCK_STREAM) ? 5: (int*)((int)(int*)((int)param0 >>> 25) & SOCK_STREAM) ? 6: (int*)((int)(int*)((int)param0 >>> 24) & SOCK_STREAM) ? 7: (int*)((int)(int*)((int)param0 >>> 23) & SOCK_STREAM) ? 8: (int*)((int)(int*)((int)param0 >>> 22) & SOCK_STREAM) ? 9: (int*)((int)(int*)((int)param0 >>> 21) & SOCK_STREAM) ? 10: (int*)((int)(int*)((int)param0 >>> 20) & SOCK_STREAM) ? 11: (int*)((int)(int*)((int)param0 >>> 19) & SOCK_STREAM) ? 12: (int*)((int)(int*)((int)param0 >>> 18) & SOCK_STREAM) ? 13: (int*)((int)(int*)((int)param0 >>> 17) & SOCK_STREAM) ? 14: (int*)((int)(int*)((int)param0 >>> 16) & SOCK_STREAM) ? 15: (int*)((int)(int*)((int)param0 >>> 15) & SOCK_STREAM) ? 16: (int*)((int)(int*)((int)param0 >>> 14) & SOCK_STREAM) ? 17: (int*)((int)(int*)((int)param0 >>> 13) & SOCK_STREAM) ? 18: (int*)((int)(int*)((int)param0 >>> 12) & SOCK_STREAM) ? 19: (int*)((int)(int*)((int)param0 >>> 11) & SOCK_STREAM) ? 20: (int*)((int)(int*)((int)param0 >>> 10) & SOCK_STREAM) ? 21: (int*)((int)(int*)((int)param0 >>> 9) & SOCK_STREAM) ? 22: (int*)((int)(int*)((int)param0 >>> 8) & SOCK_STREAM) ? 23: (int*)((int)(int*)((int)param0 >>> 7) & SOCK_STREAM) ? 24: (int*)((int)(int*)((int)param0 >>> 6) & SOCK_STREAM) ? 25: (int*)((int)(int*)((int)param0 >>> 5) & SOCK_STREAM) ? 26: (int*)((int)(int*)((int)param0 >>> 4) & SOCK_STREAM) ? 27: (int*)((int)(int*)((int)param0 >>> 3) & SOCK_STREAM) ? 28: (int*)((int)(int*)((int)param0 >>> 2) & SOCK_STREAM) ? 29: (int*)((int)(int*)((int)param0 >>> SOCK_STREAM) & SOCK_STREAM) ? 30: (int*)((int)param0 & SOCK_STREAM) ? 31: 32) >>> 5: 0;
}
