/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int axi_fpga_dev_open();
int __fastcall axi_fpga_dev_mmap(int a1, _DWORD *a2, int a3);
int axi_fpga_dev_release();
int __fastcall init_module(int a1, int a2, int a3);
int cleanup_module();
// int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _class_create(_DWORD, _DWORD, _DWORD); weak
// int __fastcall class_destroy(_DWORD); weak
// int __fastcall iounmap(_DWORD); weak
// int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall kfree(_DWORD); weak
// int __fastcall _release_region(_DWORD, _DWORD, _DWORD); weak
// int __fastcall kmem_cache_alloc(_DWORD, _DWORD); weak
// int cdev_add(void); weak
// int __fastcall device_create(_DWORD); weak
// int __fastcall ioremap(_DWORD, _DWORD); weak
// int printk(const char *, ...); weak
// int __fastcall unregister_chrdev_region(_DWORD, _DWORD); weak
// int __fastcall device_destroy(_DWORD, _DWORD); weak
// int __fastcall cdev_init(_DWORD, _DWORD); weak
// int __fastcall cdev_del(_DWORD); weak
// int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *axi_fpga_dev_fops = &_this_module; // weak
_UNKNOWN _this_module; // weak
int axi_fpga_dev_num; // weak
int p_axi_fpga_dev; // weak
int base_vir_mem_addr; // weak
int base_vir_addr; // weak
int axi_fpga_class; // weak
// extern _UNKNOWN iomem_resource; weak
// extern _DWORD kmalloc_caches[7]; weak


//----- (00000000) --------------------------------------------------------
int axi_fpga_dev_open()
{
  return 0;
}

//----- (00000008) --------------------------------------------------------
int __fastcall axi_fpga_dev_mmap(int a1, _DWORD *a2, int a3)
{
  unsigned int v3; // r2
  int result; // r0

  v3 = a2[9] & 0xFFFFFFC3;
  a2[10] |= 67387392u;
  a2[9] = v3;
  result = remap_pfn_range(a2, *a2, 262144, a2[1] - *a2, v3, a2, a3);
  if ( result )
  {
    printk("axi_fpga_dev_mmap error!\n");
    return -11;
  }
  return result;
}
// C80: using guessed type int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// C9C: using guessed type int __fastcall printk(_DWORD);

//----- (00000064) --------------------------------------------------------
int axi_fpga_dev_release()
{
  return 0;
}

//----- (0000006C) --------------------------------------------------------
int __fastcall init_module(int a1, int a2, int a3)
{
  int v3; // r5
  const char *v4; // r0
  int v5; // r0
  const char *v6; // r0
  int v8; // r1
  int v9; // r1
  unsigned int v10; // r0

  printk("In axi fpga driver!\n");
  v3 = alloc_chrdev_region(&axi_fpga_dev_num, 0, 1, "axi_fpga_dev", a1, a2, a3);
  if ( v3 < 0 )
  {
    v4 = "alloc axi_fpga_dev fail!\n";
LABEL_7:
    printk(v4);
    return v3;
  }
  v5 = kmem_cache_alloc(kmalloc_caches[6], 37748928);
  p_axi_fpga_dev = v5;
  if ( !v5 )
  {
    v6 = "kmalloc cdev fail!\n";
LABEL_11:
    printk(v6);
    return 1;
  }
  cdev_init(v5, &axi_fpga_dev_fops);
  *(_DWORD *)(p_axi_fpga_dev + 36) = &_this_module;
  v3 = cdev_add();
  if ( v3 )
  {
    v4 = "add axi_fpga_dev fail!\n";
    goto LABEL_7;
  }
  base_vir_mem_addr = _request_region(&iomem_resource, 1073741824, 5120, "axi_fpga_vir_mem", 0);
  if ( !base_vir_mem_addr )
  {
    v6 = "request_mem_region failed!\n";
    goto LABEL_11;
  }
  printk("request_mem_region OK!\n");
  v8 = ioremap(1073741824, 5120);
  base_vir_addr = v8;
  if ( v8 )
  {
    printk("AXI fpga dev virtual address is 0x%x\n", v8);
    v9 = *(_DWORD *)base_vir_addr;
    __dsb(15u);
    printk("*base_vir_addr = 0x%x\n", v9);
    v10 = _class_create(&_this_module, "axi_fpga_dev", &axi_fpga_class);
    axi_fpga_class = v10;
    if ( v10 <= 4294963200 )
    {
      device_create(v10);
      return v3;
    }
    printk("Err:failed in creating axi fpga class.\n");
  }
  else
  {
    printk("ioremap fail!\n");
    printk("!!!*base_vir_addr = 0x%x\n", base_vir_addr);
  }
  return -1;
}
// 280: using guessed type void *axi_fpga_dev_fops;
// C58: using guessed type int axi_fpga_dev_num;
// C5C: using guessed type int p_axi_fpga_dev;
// C60: using guessed type int base_vir_mem_addr;
// C64: using guessed type int base_vir_addr;
// C68: using guessed type int axi_fpga_class;
// C6C: using guessed type int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// C70: using guessed type int __fastcall _class_create(_DWORD, _DWORD, _DWORD);
// C8C: using guessed type int __fastcall kmem_cache_alloc(_DWORD, _DWORD);
// C90: using guessed type int cdev_add(void);
// C94: using guessed type int __fastcall device_create(_DWORD);
// C98: using guessed type int __fastcall ioremap(_DWORD, _DWORD);
// C9C: using guessed type int printk(const char *, ...);
// CAC: using guessed type int __fastcall cdev_init(_DWORD, _DWORD);
// CB0: using guessed type _DWORD kmalloc_caches[7];
// CB8: using guessed type int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00000218) --------------------------------------------------------
int cleanup_module()
{
  unregister_chrdev_region(axi_fpga_dev_num, 1);
  cdev_del(p_axi_fpga_dev);
  kfree(p_axi_fpga_dev);
  iounmap(base_vir_addr);
  _release_region(&iomem_resource, 1073741824, 5120);
  device_destroy(axi_fpga_class, axi_fpga_dev_num);
  class_destroy(axi_fpga_class);
  return printk("Bye Bye axi fpga driver!\n");
}
// C58: using guessed type int axi_fpga_dev_num;
// C5C: using guessed type int p_axi_fpga_dev;
// C64: using guessed type int base_vir_addr;
// C68: using guessed type int axi_fpga_class;
// C78: using guessed type int __fastcall class_destroy(_DWORD);
// C7C: using guessed type int __fastcall iounmap(_DWORD);
// C84: using guessed type int __fastcall kfree(_DWORD);
// C88: using guessed type int __fastcall _release_region(_DWORD, _DWORD, _DWORD);
// C9C: using guessed type int printk(const char *, ...);
// CA0: using guessed type int __fastcall unregister_chrdev_region(_DWORD, _DWORD);
// CA4: using guessed type int __fastcall device_destroy(_DWORD, _DWORD);
// CB4: using guessed type int __fastcall cdev_del(_DWORD);

// nfuncs=22 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
