/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'bmminer'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct $44840292B0FD4432816E14C2BB6B9957;
union $F802AEB59326FE5752476AC56FC6EFE2;
union $F85E194B51CBDC38F209555F4162D10C;
union $781B27F37A2DA3C5D0084E69F313DC7D;
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4;
union $738A8E8AC168E5B4B1A53622C9D7048F;
struct siginfo;

/* 1 */
struct __attribute__((aligned(4))) Elf32_Sym
{
  unsigned __int32 st_name;
  unsigned __int32 st_value;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct __attribute__((aligned(4))) Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file;
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 6 */
struct __attribute__((aligned(4))) Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name;
  unsigned __int32 vna_next;
};

/* 8 */
typedef struct $44840292B0FD4432816E14C2BB6B9957 __sigset_t;

/* 7 */
typedef __sigset_t sigset_t;

/* 9 */
struct $44840292B0FD4432816E14C2BB6B9957
{
  unsigned int __val[32];
};

/* 10 */
typedef union $F802AEB59326FE5752476AC56FC6EFE2 sem_t;

/* 11 */
union $F802AEB59326FE5752476AC56FC6EFE2
{
  char __size[16];
  int __align;
};

/* 12 */
typedef union $F85E194B51CBDC38F209555F4162D10C pthread_mutex_t;

/* 17 */
struct __pthread_internal_slist
{
  struct __pthread_internal_slist *__next;
};

/* 16 */
typedef struct __pthread_internal_slist __pthread_slist_t;

/* 15 */
union $::__pthread_mutex_s::$30DFB618E49C377A3D62C6584A4CBE95
{
  int __spins;
  __pthread_slist_t __list;
};

/* 14 */
struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  int __kind;
  unsigned int __nusers;
  union
  {
    int __spins;
    __pthread_slist_t __list;
  };
};

/* 13 */
union $F85E194B51CBDC38F209555F4162D10C
{
  struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s __data;
  char __size[24];
  int __align;
};

/* 19 */
typedef unsigned __int16 sa_family_t;

/* 18 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 20 */
typedef union $781B27F37A2DA3C5D0084E69F313DC7D pthread_attr_t;

/* 21 */
union $781B27F37A2DA3C5D0084E69F313DC7D
{
  char __size[36];
  int __align;
};

/* 22 */
typedef union $1C4035FDEAFFF0FCE26E66A96F6BBEB4 pthread_cond_t;

/* 24 */
struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E
{
  int __lock;
  unsigned int __futex;
  unsigned __int64 __total_seq;
  unsigned __int64 __wakeup_seq;
  unsigned __int64 __woken_seq;
  void *__mutex;
  unsigned int __nwaiters;
  unsigned int __broadcast_seq;
};

/* 23 */
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4
{
  struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E __data;
  char __size[48];
  __int64 __align;
};

/* 25 */
struct sysinfo
{
  int uptime;
  unsigned int loads[3];
  unsigned int totalram;
  unsigned int freeram;
  unsigned int sharedram;
  unsigned int bufferram;
  unsigned int totalswap;
  unsigned int freeswap;
  unsigned __int16 procs;
  unsigned __int16 pad;
  unsigned int totalhigh;
  unsigned int freehigh;
  unsigned int mem_unit;
  char _f[8];
};

/* 26 */
typedef union $738A8E8AC168E5B4B1A53622C9D7048F pthread_rwlock_t;

/* 28 */
struct $738A8E8AC168E5B4B1A53622C9D7048F::$D6587128ED4C013AF36DCCA432989BD5
{
  int __lock;
  unsigned int __nr_readers;
  unsigned int __readers_wakeup;
  unsigned int __writer_wakeup;
  unsigned int __nr_readers_queued;
  unsigned int __nr_writers_queued;
  unsigned int __flags;
  int __writer;
};

/* 27 */
union $738A8E8AC168E5B4B1A53622C9D7048F
{
  struct $738A8E8AC168E5B4B1A53622C9D7048F::$D6587128ED4C013AF36DCCA432989BD5 __data;
  char __size[32];
  int __align;
};

/* 29 */
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
  int tm_gmtoff;
  const char *tm_zone;
};

/* 31 */
typedef int __time_t;

/* 30 */
struct timespec
{
  __time_t tv_sec;
  int tv_nsec;
};

/* 32 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 33 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 34 */
typedef __n64 int8x8_t;

/* 35 */
typedef __n64 uint8x8_t;

/* 36 */
typedef __n64 int16x4_t;

/* 37 */
typedef __n64 int32x2_t;

/* 38 */
typedef __n64 uint16x4_t;

/* 39 */
typedef __n64 uint32x2_t;

/* 40 */
typedef __n128 int8x16_t;

/* 41 */
typedef __n128 int16x8_t;

/* 42 */
typedef __n128 int32x4_t;

/* 43 */
typedef __n128 int64x2_t;

/* 44 */
typedef __n128 uint8x16_t;

/* 45 */
typedef __n128 uint16x8_t;

/* 46 */
typedef __n128 uint32x4_t;

/* 47 */
typedef __n128 uint64x2_t;

/* 48 */
typedef __n64 poly8x8_t;

/* 49 */
typedef __n64 poly16x4_t;

/* 50 */
typedef __n128 poly16x8_t;

/* 51 */
typedef __n128 poly8x16_t;

/* 52 */
typedef __n64 float32x2_t;

/* 53 */
typedef __n128 float32x4_t;

/* 54 */
typedef __n128 float64x2_t;

/* 55 */
typedef __n128 poly128_t;

/* 58 */
typedef void (*__sighandler_t)(int);

/* 59 */
typedef struct siginfo siginfo_t;

/* 57 */
union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68
{
  __sighandler_t sa_handler;
  void (*sa_sigaction)(int, siginfo_t *, void *);
};

/* 56 */
struct sigaction
{
  union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68 __sigaction_handler;
  __sigset_t sa_mask;
  int sa_flags;
  void (*sa_restorer)(void);
};

/* 63 */
typedef int __pid_t;

/* 64 */
typedef unsigned int __uid_t;

/* 62 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3
{
  __pid_t si_pid;
  __uid_t si_uid;
};

/* 67 */
union sigval
{
  int sival_int;
  void *sival_ptr;
};

/* 66 */
typedef union sigval sigval_t;

/* 65 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065
{
  int si_tid;
  int si_overrun;
  sigval_t si_sigval;
};

/* 68 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2
{
  __pid_t si_pid;
  __uid_t si_uid;
  sigval_t si_sigval;
};

/* 70 */
typedef int __clock_t;

/* 69 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6
{
  __pid_t si_pid;
  __uid_t si_uid;
  int si_status;
  __clock_t si_utime;
  __clock_t si_stime;
};

/* 71 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC
{
  void *si_addr;
};

/* 72 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3
{
  int si_band;
  int si_fd;
};

/* 61 */
union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43
{
  int _pad[29];
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3 _kill;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065 _timer;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2 _rt;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6 _sigchld;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC _sigfault;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3 _sigpoll;
};

/* 60 */
struct siginfo
{
  int si_signo;
  int si_errno;
  int si_code;
  union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43 _sifields;
};

