/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_105D8();
// int strcmp(const char *s1, const char *s2);
// int strtol(const char *nptr, char **endptr, int base);
// int printf(const char *format, ...);
// void *realloc(void *ptr, size_t size);
// int __fastcall _rawmemchr(_DWORD, _DWORD); weak
// int puts(const char *s);
// void *malloc(size_t size);
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// char *strerror(int errnum);
// int _gmon_start__(void); weak
// const unsigned __int16 **_ctype_b_loc(void);
// size_t strlen(const char *s);
// char *strchr(const char *s, int c);
// int fprintf(FILE *stream, const char *format, ...);
// int *_errno_location(void);
// int socket(int domain, int type, int protocol);
// struct hostent *gethostbyname(const char *name);
// void abort(void);
// ssize_t recv(int fd, void *buf, size_t n, int flags);
// int close(int fd);
// ssize_t send(int fd, const void *buf, size_t n, int flags);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
int __fastcall main(int, char **, char **); // idb
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...);
int sub_108B8();
int *sub_108DC();
__int64 sub_10900();
int *sub_1092C();
unsigned __int8 *__fastcall sub_10948(unsigned __int8 *a1);
char *__fastcall sub_109B8(char *result);
int __fastcall sub_10B4C(const char *a1, char *name, unsigned int a3);
int __fastcall init(int a1, int a2, int a3);
int nullsub_1(); // weak
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

void *off_21F10 = (void *)0x10945; // weak
int stderr; // weak
char byte_22074; // weak
int dword_22078; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (000105CC) --------------------------------------------------------
int init_proc()
{
  return sub_108B8();
}

//----- (000105D8) --------------------------------------------------------
void sub_105D8()
{
  JUMPOUT(0);
}
// 105E4: control flows out of bounds to 0

//----- (000106F4) --------------------------------------------------------
int __fastcall main(int a1, char **a2, char **a3)
{
  char *v3; // r5
  int v6; // r5
  unsigned __int8 *v7; // r0
  const char *v8; // r7
  char **v9; // r4
  int v10; // r8
  char *v11; // r5
  unsigned __int8 *v12; // r0
  unsigned __int8 *v13; // r0
  unsigned int v14; // r2
  int v15; // r7

  if ( a1 <= 1 )
    goto LABEL_20;
  v3 = a2[1];
  if ( *v3 == 45 )
  {
    v15 = (unsigned __int8)v3[1];
    if ( v15 == 63 )
    {
      if ( !v3[2] )
        goto LABEL_24;
    }
    else if ( v15 == 104 )
    {
      if ( !v3[2] )
        goto LABEL_24;
      goto LABEL_3;
    }
    if ( !strcmp(v3, "--help") )
      goto LABEL_24;
    if ( v15 != 111 || v3[2] )
      goto LABEL_4;
    dword_22078 = 1;
    if ( a1 != 2 )
    {
      v6 = 2;
      goto LABEL_5;
    }
LABEL_20:
    v11 = "127.0.0.1";
    v8 = "summary";
    v14 = 4028;
    return sub_10B4C(v8, v11, v14);
  }
LABEL_3:
  if ( strcmp(v3, "--help") )
  {
LABEL_4:
    v6 = 1;
LABEL_5:
    v7 = sub_10948((unsigned __int8 *)a2[v6]);
    v8 = "summary";
    if ( *v7 )
      v8 = (const char *)v7;
    if ( a1 <= v6 + 1 )
    {
      v11 = "127.0.0.1";
      v14 = 4028;
    }
    else
    {
      v9 = &a2[v6];
      v10 = v6 + 2;
      v11 = "127.0.0.1";
      v12 = sub_10948((unsigned __int8 *)v9[1]);
      if ( *v12 )
        v11 = (char *)v12;
      if ( a1 > v10 && (v13 = sub_10948((unsigned __int8 *)v9[2]), *v13) )
        v14 = (__int16)strtol((const char *)v13, 0, 10);
      else
        v14 = 4028;
    }
    return sub_10B4C(v8, v11, v14);
  }
LABEL_24:
  fprintf((FILE *)stderr, "usAge: %s [command [ip/host [port]]]\n", *a2);
  return 1;
}
// 22070: using guessed type int stderr;
// 22078: using guessed type int dword_22078;

//----- (00010888) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(void), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main(main, v4, (char **)va, (void (*)(void))init, (void (*)(void))nullsub_1, a1, va);
  abort();
}
// 10892: positive sp value 4 has been found
// 108A4: variable 'v4' is possibly undefined
// 10D9C: using guessed type int init();
// 10DD8: using guessed type int nullsub_1();

//----- (000108B8) --------------------------------------------------------
int sub_108B8()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 10658: using guessed type int _gmon_start__(void);

//----- (000108DC) --------------------------------------------------------
int *sub_108DC()
{
  return &stderr;
}
// 22070: using guessed type int stderr;

//----- (00010900) --------------------------------------------------------
__int64 sub_10900()
{
  __int64 result; // r0

  LODWORD(result) = &stderr;
  HIDWORD(result) = 0;
  return result;
}
// 22070: using guessed type int stderr;

//----- (0001092C) --------------------------------------------------------
int *sub_1092C()
{
  int *result; // r0

  if ( !byte_22074 )
  {
    result = sub_108DC();
    byte_22074 = 1;
  }
  return result;
}
// 22074: using guessed type char byte_22074;

//----- (00010948) --------------------------------------------------------
unsigned __int8 *__fastcall sub_10948(unsigned __int8 *a1)
{
  const unsigned __int16 **v2; // r6
  unsigned __int8 *v3; // r0
  int v4; // r3
  unsigned __int8 *v5; // r5
  unsigned __int8 *v6; // r0
  int v7; // t1

  v2 = _ctype_b_loc();
  v3 = a1;
  do
  {
    v4 = *v3;
    v5 = v3++;
  }
  while ( ((*v2)[v4] & 0x2000) != 0 );
  v6 = (unsigned __int8 *)_rawmemchr(v5, 0);
  while ( v5 < v6 )
  {
    v7 = *--v6;
    if ( ((*v2)[v7] & 0x2000) != 0 )
      *v6 = 0;
  }
  return v5;
}
// 1061C: using guessed type int __fastcall _rawmemchr(_DWORD, _DWORD);

//----- (000109B8) --------------------------------------------------------
char *__fastcall sub_109B8(char *result)
{
  const char *v1; // r4
  const char *v2; // r7
  int v3; // r6
  const char *v4; // r5
  char *v5; // r0
  char *v6; // r11
  char *v7; // r2
  const char *v8; // r1
  char *v9; // r0
  const char *v10; // r2

  v1 = result;
  if ( !result )
    return result;
  do
  {
    result = strchr(v1, 124);
    if ( result )
    {
      v2 = result + 1;
      *result = 0;
      if ( !*v1 )
      {
        v1 = result + 1;
        continue;
      }
    }
    else
    {
      if ( !*v1 )
        return result;
      v2 = 0;
    }
    v3 = 0;
    while ( 1 )
    {
      v9 = strchr(v1, 44);
      if ( !v9 )
        break;
      v4 = v9 + 1;
      *v9 = 0;
      if ( !*v1 )
      {
        v1 = v9 + 1;
        goto LABEL_21;
      }
LABEL_13:
      v5 = strchr(v1, 61);
      v6 = v5;
      if ( !v5 )
      {
        if ( !v3 )
LABEL_29:
          printf("[%s%s] =>\n(\n", v1, "");
LABEL_27:
        v10 = v1;
        v1 = v4;
        printf("   [%d] => %s\n", v3, v10);
        goto LABEL_21;
      }
      *v5 = 0;
      if ( v3 )
      {
        if ( v5 == (char *)-1 )
          goto LABEL_27;
      }
      else
      {
        if ( v5 == (char *)-1 )
          goto LABEL_29;
        if ( ((*_ctype_b_loc())[(unsigned __int8)v5[1]] & 0x800) != 0 )
          v7 = v6 + 1;
        else
          v7 = "";
        printf("[%s%s] =>\n(\n", v1, v7);
      }
      v8 = v1;
      v1 = v4;
      printf("   [%s] => %s\n", v8, v6 + 1);
LABEL_21:
      ++v3;
      if ( !v4 )
        goto LABEL_25;
    }
    if ( *v1 )
    {
      v4 = 0;
      goto LABEL_13;
    }
LABEL_25:
    v1 = v2;
    result = (char *)puts(")");
  }
  while ( v2 );
  return result;
}

//----- (00010B4C) --------------------------------------------------------
int __fastcall sub_10B4C(const char *a1, char *name, unsigned int a3)
{
  struct hostent *v6; // r7
  int v7; // r0
  int v8; // r8
  int v9; // r4
  char **h_addr_list; // r3
  int v11; // r3
  size_t v12; // r0
  char *v13; // r9
  int v14; // r7
  char *v15; // r6
  ssize_t v16; // r0
  int v17; // r5
  int v18; // r5
  size_t v19; // r1
  int *v21; // r0
  char *v22; // r0
  int *v23; // r0
  char *v24; // r0
  int *v25; // r0
  char *v26; // r0
  int *v27; // r0
  char *v28; // r0
  struct sockaddr v29[3]; // [sp+0h] [bp-30h] BYREF

  v6 = gethostbyname(name);
  if ( !v6 )
  {
    printf("Couldn't get hostname: '%s'\n", name);
    return 1;
  }
  v7 = socket(2, 1, 0);
  v8 = v7;
  if ( v7 == -1 )
  {
    v21 = _errno_location();
    v22 = strerror(*v21);
    printf("Socket initialisation failed: %s\n", v22);
    return 1;
  }
  v9 = 0;
  h_addr_list = v6->h_addr_list;
  memset(v29[0].sa_data, 0, sizeof(v29[0].sa_data));
  v29[0].sa_family = 2;
  v11 = *(_DWORD *)*h_addr_list;
  *(_DWORD *)v29[0].sa_data = (unsigned __int16)__rev16(a3);
  *(_DWORD *)&v29[0].sa_data[2] = v11;
  if ( connect(v7, v29, 16u) < 0 )
  {
    v23 = _errno_location();
    v24 = strerror(*v23);
    printf("Socket connect failed: %s\n", v24);
    return 1;
  }
  v12 = strlen(a1);
  if ( send(v8, a1, v12, 0) >= 0 )
  {
    v13 = (char *)malloc(65536u);
    if ( v13 )
    {
      v14 = 65535;
      while ( 1 )
      {
        v15 = &v13[v9];
        v16 = recv(v8, &v13[v9], v14 - v9, 0);
        v17 = v16;
        v9 += v16;
        if ( v16 < 0 )
          break;
        if ( !v16 )
          goto LABEL_18;
        if ( v14 == v9 )
        {
          v18 = v14 + 65536;
          v19 = v14 + 65536;
          v14 += 65535;
          v13 = (char *)realloc(v13, v19);
          if ( !v13 )
          {
            printf("Err: OOM (%d)\n", v18);
            return 1;
          }
        }
      }
      v25 = _errno_location();
      v17 = 1;
      v26 = strerror(*v25);
      printf("Recv failed: %s\n", v26);
LABEL_18:
      *v15 = 0;
      if ( dword_22078 )
      {
        puts(v13);
      }
      else
      {
        printf("Reply was '%s'\n", v13);
        sub_109B8(v13);
      }
      goto LABEL_20;
    }
    printf("Err: OOM (%d)\n", 65536);
    return 1;
  }
  v27 = _errno_location();
  v17 = 1;
  v28 = strerror(*v27);
  printf("Send failed: %s\n", v28);
LABEL_20:
  close(v8);
  return v17;
}
// 22078: using guessed type int dword_22078;

//----- (00010D9C) --------------------------------------------------------
int __fastcall init(int a1, int a2, int a3)
{
  void **v6; // r5
  int i; // r4
  int (__fastcall *v8)(int, int, int); // t1
  int result; // r0

  init_proc();
  v6 = &off_21F10;
  for ( i = 0; i != 1; ++i )
  {
    v8 = (int (__fastcall *)(int, int, int))*v6++;
    result = v8(a1, a2, a3);
  }
  return result;
}
// 21F10: using guessed type void *off_21F10;

//----- (00010DDC) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=59 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
