//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct hostent {
    char * e0;
    char ** e1;
    int32_t e2;
    int32_t e3;
    char ** e4;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t a1, int32_t a2);
int32_t function_105cc(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_105ec(char * s1, char * s2);
int32_t function_105f8(char * nptr, char ** endptr, int32_t base);
int32_t function_10604(char * format, ...);
int32_t * function_10610(int32_t * ptr, int32_t size);
int32_t * function_1061c(int32_t * s, int32_t c);
int32_t function_10628(char * s);
int32_t * function_10634(int32_t size);
int32_t function_10640(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
char * function_1064c(int32_t errnum);
void function_10658(void);
int16_t ** function_10664(void);
int32_t function_10670(char * s);
char * function_1067c(char * s, int32_t c);
int32_t function_10688(struct _IO_FILE * stream, char * format, ...);
int32_t * function_10694(void);
int32_t function_106a0(int32_t domain, int32_t type, int32_t protocol);
struct hostent * function_106ac(char * name);
void function_106b8(void);
int32_t function_106c4(int32_t fd, int32_t * buf, int32_t n, int32_t flags);
int32_t function_106d0(int32_t fd);
int32_t function_106dc(int32_t fd, int32_t * buf, int32_t n, int32_t flags);
int32_t function_106e8(int32_t fd, struct sockaddr * addr, int32_t len);
int32_t function_106f4(uint32_t a1, int32_t a2);
int32_t function_108ac(int32_t result, int32_t a2, int32_t a3, int32_t a4);
int32_t function_108b8(void);
int32_t function_108dc(int32_t result, int32_t a2, int32_t a3, int32_t a4);
int32_t function_10938(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_10944(void);
int32_t function_10948(int32_t a1);
int32_t function_109b8(int32_t a1);
int32_t function_10b4c(int32_t str, int32_t a2, int32_t a3);
int32_t function_10d9c(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_10dd8(void);
int32_t function_10ddc(int32_t result, int32_t a2, int32_t a3, int32_t a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char * g1; // 0x10e38
int32_t g2 = 0x10945; // 0x21f10
int32_t g3 = 0; // 0x22064
struct _IO_FILE * g4 = NULL; // 0x22070
int32_t g5 = 0; // 0x22078
int32_t g6;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
int32_t * __rawmemchr(int32_t * a1, int32_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x105cc - 0x105d8
int32_t function_105cc(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x105cc
    return function_108b8();
}

// Address range: 0x105ec - 0x105f8
int32_t function_105ec(char * s1, char * s2) {
    // 0x105ec
    return strcmp(s1, s2);
}

// Address range: 0x105f8 - 0x10604
int32_t function_105f8(char * nptr, char ** endptr, int32_t base) {
    // 0x105f8
    return strtol(nptr, endptr, base);
}

// Address range: 0x10604 - 0x10610
int32_t function_10604(char * format, ...) {
    // 0x10604
    return printf(format);
}

// Address range: 0x10610 - 0x1061c
int32_t * function_10610(int32_t * ptr, int32_t size) {
    // 0x10610
    return realloc(ptr, size);
}

// Address range: 0x1061c - 0x10628
int32_t * function_1061c(int32_t * s, int32_t c) {
    // 0x1061c
    return __rawmemchr(s, c);
}

// Address range: 0x10628 - 0x10634
int32_t function_10628(char * s) {
    // 0x10628
    return puts(s);
}

// Address range: 0x10634 - 0x10640
int32_t * function_10634(int32_t size) {
    // 0x10634
    return malloc(size);
}

// Address range: 0x10640 - 0x1064c
int32_t function_10640(int32_t main, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10640
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1064c - 0x10658
char * function_1064c(int32_t errnum) {
    // 0x1064c
    return strerror(errnum);
}

// Address range: 0x10658 - 0x10664
void function_10658(void) {
    // 0x10658
    __gmon_start__();
}

// Address range: 0x10664 - 0x10670
int16_t ** function_10664(void) {
    // 0x10664
    return __ctype_b_loc();
}

// Address range: 0x10670 - 0x1067c
int32_t function_10670(char * s) {
    // 0x10670
    return strlen(s);
}

// Address range: 0x1067c - 0x10688
char * function_1067c(char * s, int32_t c) {
    // 0x1067c
    return strchr(s, c);
}

// Address range: 0x10688 - 0x10694
int32_t function_10688(struct _IO_FILE * stream, char * format, ...) {
    // 0x10688
    return fprintf(stream, format);
}

// Address range: 0x10694 - 0x106a0
int32_t * function_10694(void) {
    // 0x10694
    return __errno_location();
}

// Address range: 0x106a0 - 0x106ac
int32_t function_106a0(int32_t domain, int32_t type, int32_t protocol) {
    // 0x106a0
    return socket(domain, type, protocol);
}

// Address range: 0x106ac - 0x106b8
struct hostent * function_106ac(char * name) {
    // 0x106ac
    return gethostbyname(name);
}

// Address range: 0x106b8 - 0x106c4
void function_106b8(void) {
    // 0x106b8
    abort();
}

// Address range: 0x106c4 - 0x106d0
int32_t function_106c4(int32_t fd, int32_t * buf, int32_t n, int32_t flags) {
    // 0x106c4
    return recv(fd, buf, n, flags);
}

// Address range: 0x106d0 - 0x106dc
int32_t function_106d0(int32_t fd) {
    // 0x106d0
    return close(fd);
}

// Address range: 0x106dc - 0x106e8
int32_t function_106dc(int32_t fd, int32_t * buf, int32_t n, int32_t flags) {
    // 0x106dc
    return send(fd, buf, n, flags);
}

// Address range: 0x106e8 - 0x106f4
int32_t function_106e8(int32_t fd, struct sockaddr * addr, int32_t len) {
    // 0x106e8
    return connect(fd, addr, len);
}

// Address range: 0x106f4 - 0x10888
int32_t function_106f4(uint32_t a1, int32_t a2) {
    // 0x106f4
    if (a1 < 2) {
        // 0x1081c
        return function_10b4c((int32_t)"summary", (int32_t)"127.0.0.1", 4028);
    }
    int32_t v1 = *(int32_t *)(a2 + 4); // 0x10700
    char * str = (char *)v1; // 0x1070c
    char v2; // 0x107a8
    if (*str == 45) {
        // 0x107a8
        v2 = *(char *)(v1 + 1);
        switch (v2) {
            case 63: {
                // 0x107b4
                if (*(char *)(v1 + 2) == 0) {
                    // 0x10840
                    fprintf(g4, "usAge: %s [command [ip/host [port]]]\n", (char *)3808);
                    return 1;
                }
                goto lab_0x107c0;
            }
            case 104: {
                // 0x10834
                if (*(char *)(v1 + 2) == 0) {
                    // 0x10840
                }
                goto lab_0x10718;
            }
            default: {
                goto lab_0x107c0;
            }
        }
    } else {
        goto lab_0x10718;
    }
  lab_0x10718:;
    int32_t v3 = 1; // 0x1072c
    if (strcmp(str, "--help") == 0) {
        // 0x10840
        fprintf(g4, "usAge: %s [command [ip/host [port]]]\n", (char *)3808);
        return 1;
    }
    goto lab_0x10734;
  lab_0x107c0:
    // 0x107c0
    if (strcmp(str, "--help") == 0) {
        // 0x10840
        fprintf(g4, "usAge: %s [command [ip/host [port]]]\n", (char *)3808);
        return 1;
    }
    // 0x107d8
    v3 = 1;
    if (v2 == 111) {
        // 0x107e0
        v3 = 1;
        if (*(char *)(v1 + 2) == 0) {
            // 0x107ec
            g5 = 1;
            v3 = 2;
            if (a1 == 2) {
                // 0x1081c
                return function_10b4c((int32_t)"summary", (int32_t)"127.0.0.1", 4028);
            }
        }
    }
    goto lab_0x10734;
  lab_0x10734:;
    int32_t v4 = 4 * v3 + a2; // 0x10734
    int32_t v5 = function_10948(*(int32_t *)v4); // 0x1073c
    int32_t v6 = *(char *)v5 == 0 ? (int32_t)"summary" : v5;
    if (v3 + 1 >= a1) {
        // 0x1081c
        return function_10b4c(v6, (int32_t)"127.0.0.1", 4028);
    }
    int32_t v7 = function_10948(*(int32_t *)(v4 + 4)); // 0x10770
    int32_t v8 = *(char *)v7 == 0 ? (int32_t)"127.0.0.1" : v7;
    if (v3 + 2 >= a1) {
        // 0x1081c
        return function_10b4c(v6, v8, 4028);
    }
    char * str2 = (char *)function_10948(*(int32_t *)(v4 + 8)); // 0x10794
    int32_t v9 = 4028; // 0x1079c
    if (*str2 != 0) {
        // 0x10864
        v9 = __asm_sxth(strtol(str2, NULL, 10));
    }
    // 0x1081c
    return function_10b4c(v6, v8, v9);
}

// Address range: 0x10888 - 0x108ac
int32_t entry_point(int32_t a1, int32_t a2) {
    // 0x10888
    int32_t v1; // 0x10888
    __libc_start_main(0x106f4, a2, (char **)&v1, (void (*)())0x10d9d, (void (*)())0x106f4, (void (*)())a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x108ac - 0x108b0
int32_t function_108ac(int32_t result, int32_t a2, int32_t a3, int32_t a4) {
    // 0x108ac
    return result;
}

// Address range: 0x108b8 - 0x108d4
int32_t function_108b8(void) {
    // 0x108b8
    if (g3 == 0) {
        int32_t result; // 0x108b8
        return result;
    }
    // 0x108d0
    __gmon_start__();
    return &g6;
}

// Address range: 0x108dc - 0x10938
int32_t function_108dc(int32_t result, int32_t a2, int32_t a3, int32_t a4) {
    // 0x108dc
    bool v1; // 0x108dc
    if (v1) {
        return result;
    }
    // 0x1090c
    int32_t v2; // 0x108dc
    int32_t v3 = 0x100001 * v2; // 0x10910
    bool v4; // 0x108dc
    int32_t v5; // 0x108dc
    if (v1) {
        // .thread
        v5 = v1 ? v3 : 0;
    } else {
        int32_t v6 = v3 & -1 - 0x400000 * v2; // 0x10914
        v5 = v6 < 1 ? 0 : v3;
        v4 = v6 < 0;
        if (v6 == 0) {
            return unknown_240();
        }
    }
    // 0x10924
    if (v4 != v1) {
        __asm_svclt(0x4770);
    }
    float64_t v7; // 0x108dc
    __asm_vqrshl_s8(v7, v7);
    __asm_vmvn_i32(0x40000);
    if (!v1) {
        *(int32_t *)a4 = v5;
    }
    return result;
}

// Address range: 0x10938 - 0x10944
int32_t function_10938(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t result = a1; // 0x10938
    if (a4 == 0) {
        // 0x1093a
        result = function_108dc(a1, a2, a3, 0);
        int32_t v1; // 0x10938
        *(char *)v1 = 1;
    }
    // 0x10942
    return result;
}

// Address range: 0x10944 - 0x10946
int32_t function_10944(void) {
    // 0x10944
    int32_t result; // 0x10944
    return result;
}

// Address range: 0x10948 - 0x109b8
int32_t function_10948(int32_t a1) {
    int16_t ** v1 = __ctype_b_loc(); // 0x10950
    int32_t v2 = (int32_t)*v1; // 0x10958
    uint32_t result = a1; // 0x1095c
    while ((*(int16_t *)(2 * (int32_t)*(char *)result + v2) & 0x2000) != 0) {
        // 0x10960
        result++;
    }
    int32_t v3 = (int32_t)__rawmemchr((int32_t *)result, 0); // 0x10984
    if (result >= v3) {
        // 0x109b0
        return result;
    }
    int32_t v4 = v3; // 0x10990
    v4--;
    char * v5 = (char *)v4; // 0x10990
    if ((*(int16_t *)(2 * (int32_t)*v5 + (int32_t)*v1) & 0x2000) != 0) {
        *v5 = 0;
    }
    while (result < v4) {
        // 0x10990
        v4--;
        v5 = (char *)v4;
        if ((*(int16_t *)(2 * (int32_t)*v5 + (int32_t)*v1) & 0x2000) != 0) {
            *v5 = 0;
        }
    }
    // 0x109b0
    return result;
}

// Address range: 0x109b8 - 0x10b4c
int32_t function_109b8(int32_t a1) {
    // 0x109b8
    if (a1 == 0) {
        // 0x10a1c
        return 0;
    }
    int32_t v1 = a1; // 0x109c4
    int32_t puts_rc; // 0x109b8
    int32_t result; // 0x109b8
    int32_t v2; // 0x109b8
    int32_t v3; // 0x109b8
    int32_t v4; // 0x109b8
    while (true) {
      lab_0x109e4:
        // 0x109e4
        v2 = v1;
        char * str = (char *)v2; // 0x109ec
        char * found_char_pos = strchr(str, 124); // 0x109ec
        int32_t v5 = (int32_t)found_char_pos; // 0x109ec
        if (found_char_pos == NULL) {
            // 0x10a24
            result = v5;
            v4 = v5;
            if (*str == 0) {
                // break -> 0x10a1c
                break;
            }
            goto lab_0x10a34;
        } else {
            int32_t v6 = v5 + 1; // 0x109fc
            *found_char_pos = 0;
            puts_rc = v5;
            v3 = v6;
            v4 = v6;
            if (*str == 0) {
                goto lab_0x10a14;
            } else {
                goto lab_0x10a34;
            }
        }
    }
  lab_0x10a1c:
    // 0x10a1c
    return result;
  lab_0x10a58:;
    // 0x10a58
    int32_t v7; // 0x109b8
    int32_t v8 = v7;
    char * str2; // 0x109b8
    char * found_char_pos2 = strchr(str2, 61); // 0x10a60
    char * v9; // 0x109b8
    int32_t v10; // 0x109b8
    int32_t v11; // 0x109b8
    if (found_char_pos2 == NULL) {
        if (v11 == 0) {
            // 0x10b38
            printf("[%s%s] =>\n(\n", str2, (char *)&g1);
            // 0x10b18
            printf("   [%d] => %s\n", v11, str2);
            v10 = v8;
            goto lab_0x10acc;
        } else {
            // 0x10b18
            printf("   [%d] => %s\n", v11, str2);
            v10 = v8;
            goto lab_0x10acc;
        }
    } else {
        // 0x10a6c
        *found_char_pos2 = 0;
        int32_t v12 = (int32_t)found_char_pos2 + 1; // 0x10a78
        if (v11 == 0) {
            if (v12 == 0) {
                // 0x10b38
                printf("[%s%s] =>\n(\n", str2, (char *)&g1);
                // 0x10b18
                printf("   [%d] => %s\n", v11, str2);
                v10 = v8;
                goto lab_0x10acc;
            } else {
                int16_t ** v13 = __ctype_b_loc(); // 0x10a88
                char * v14 = (char *)v12;
                int16_t v15 = *(int16_t *)(2 * (int32_t)*v14 + (int32_t)*v13); // 0x10aa0
                printf("[%s%s] =>\n(\n", str2, (v15 & 2048) == 0 ? (char *)&g1 : v14);
                v9 = v14;
                goto lab_0x10ab4;
            }
        } else {
            if (v12 == 0) {
                // 0x10b18
                printf("   [%d] => %s\n", v11, str2);
                v10 = v8;
                goto lab_0x10acc;
            } else {
                // 0x10b10
                v9 = (char *)v12;
                goto lab_0x10ab4;
            }
        }
    }
  lab_0x10acc:;
    int32_t v16 = v10; // 0x10ad4
    int32_t v17 = v11 + 1; // 0x10ad4
    if (v10 == 0) {
        // break -> 0x10afc
        goto lab_0x10afc;
    }
    goto lab_0x10ad8;
  lab_0x10ab4:
    // 0x10ab4
    printf("   [%s] => %s\n", str2, v9);
    v10 = v8;
    goto lab_0x10acc;
  lab_0x10a34:
    // 0x10a34
    v16 = v2;
    v17 = 0;
    while (true) {
      lab_0x10ad8:
        // 0x10ad8
        v11 = v17;
        str2 = (char *)v16;
        char * found_char_pos3 = strchr(str2, 44); // 0x10ae0
        int32_t v18 = (int32_t)found_char_pos3; // 0x10ae0
        if (found_char_pos3 == NULL) {
            // 0x10aec
            v7 = v18;
            if (*str2 == 0) {
                // break -> 0x10afc
                break;
            }
            goto lab_0x10a58;
        } else {
            int32_t v19 = v18 + 1; // 0x10a40
            *found_char_pos3 = 0;
            v7 = v19;
            v10 = v19;
            if (*str2 == 0) {
                goto lab_0x10acc;
            } else {
                goto lab_0x10a58;
            }
        }
    }
  lab_0x10afc:
    // 0x10afc
    puts_rc = puts(")");
    v3 = v4;
    goto lab_0x10a14;
  lab_0x10a14:
    // 0x10a14
    v1 = v3;
    result = puts_rc;
    if (v1 == 0) {
        // break -> 0x10a1c
        goto lab_0x10a1c;
    }
    goto lab_0x109e4;
}

// Address range: 0x10b4c - 0x10d9c
int32_t function_10b4c(int32_t str, int32_t a2, int32_t a3) {
    char * name = (char *)a2; // 0x10b64
    if (gethostbyname(name) == NULL) {
        // 0x10c74
        printf("Couldn't get hostname: '%s'\n", name);
        // 0x10c88
        return 1;
    }
    int32_t sock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10b7c
    if (sock_fd == -1) {
        // 0x10c94
        printf("Socket initialisation failed: %s\n", strerror(*__errno_location()));
        return 1;
    }
    // 0x10b8c
    __asm_rev16(a3);
    int32_t addr = 2; // bp-48, 0x10bb0
    if (connect(sock_fd, (struct sockaddr *)&addr, 16) < 0) {
        // 0x10cc0
        printf("Socket connect failed: %s\n", strerror(*__errno_location()));
        return 1;
    }
    // 0x10bd4
    if (send(sock_fd, (int32_t *)str, strlen((char *)str), 0) < 0) {
        // 0x10d44
        printf("Send failed: %s\n", strerror(*__errno_location()));
        // 0x10d30
        close(sock_fd);
        return 1;
    }
    int32_t * mem = malloc(0x10000); // 0x10bfc
    int32_t v1 = 0; // 0x10c0c
    int32_t v2 = 0xffff; // 0x10c0c
    int32_t * mem2 = mem; // 0x10c0c
    if (mem == NULL) {
        // 0x10d84
        printf("Err: OOM (%d)\n", 0x10000);
        // 0x10c88
        return 1;
    }
    int32_t result; // 0x10b4c
    int32_t v3; // 0x10b4c
    int32_t * str2; // 0x10b4c
    int32_t buf; // 0x10c10
    while (true) {
        // 0x10c10
        str2 = mem2;
        v3 = (int32_t)str2;
        int32_t v4 = v1; // 0x10c2c
        buf = v4 + v3;
        int32_t v5 = recv(sock_fd, (int32_t *)buf, v2 - v4, 0); // 0x10c24
        if (v5 < 0) {
            // break (via goto) -> 0x10cec
            goto lab_0x10cec;
        }
        // 0x10c34
        result = 0;
        if (v5 == 0) {
            goto lab_0x10d0c;
        }
        // 0x10c38
        v4 += v5;
        while (v2 != v4) {
            // 0x10c10
            buf = v4 + v3;
            v5 = recv(sock_fd, (int32_t *)buf, v2 - v4, 0);
            if (v5 < 0) {
                // break (via goto) -> 0x10cec
                goto lab_0x10cec;
            }
            // 0x10c34
            result = 0;
            if (v5 == 0) {
                goto lab_0x10d0c;
            }
            // 0x10c38
            v4 += v5;
        }
        int32_t v6 = v2 + 0x10000; // 0x10c40
        mem2 = realloc(str2, v6);
        v1 = v2;
        int32_t v7; // 0x10b4c
        v2 += (mem == NULL ? v7 : 0xffff);
        if (mem2 == NULL) {
            // 0x10c5c
            printf("Err: OOM (%d)\n", v6);
            return 1;
        }
    }
  lab_0x10cec:
    // 0x10cec
    printf("Recv failed: %s\n", strerror(*__errno_location()));
    result = 1;
  lab_0x10d0c:
    // 0x10d0c
    *(char *)buf = 0;
    if (g5 != 0) {
        // 0x10d28
        puts((char *)str2);
        // 0x10d30
        close(sock_fd);
        return result;
    }
    // 0x10d68
    printf("Reply was '%s'\n", str2);
    function_109b8(v3);
    // 0x10d30
    close(sock_fd);
    return result;
}

// Address range: 0x10d9c - 0x10dd0
int32_t function_10d9c(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = function_105cc(a1, a2, a3, a4); // 0x10dac
    return 0x21f12 - (int32_t)&g2 >> 2 == 0 ? v1 : a1;
}

// Address range: 0x10dd8 - 0x10dda
int32_t function_10dd8(void) {
    // 0x10dd8
    int32_t result; // 0x10dd8
    return result;
}

// Address range: 0x10ddc - 0x10de4
int32_t function_10ddc(int32_t result, int32_t a2, int32_t a3, int32_t a4) {
    // 0x10ddc
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 36

