/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int axi_fpga_dev_open();
int axi_fpga_dev_release();
int __fastcall axi_fpga_dev_mmap(int, _DWORD *, int); // idb
int __fastcall init_module(int a1, int a2);
int cleanup_module(); // idb
// int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _class_create(_DWORD, _DWORD, _DWORD); weak
// int __fastcall class_destroy(_DWORD); weak
// int __fastcall iounmap(_DWORD); weak
// int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall kfree(_DWORD); weak
// int __fastcall _release_region(_DWORD, _DWORD, _DWORD); weak
// int __fastcall kmem_cache_alloc(_DWORD, _DWORD); weak
// int cdev_add(void); weak
// int __fastcall device_create(_DWORD); weak
// int __fastcall ioremap(_DWORD, _DWORD); weak
// int printk(const char *, ...); weak
// int __fastcall unregister_chrdev_region(_DWORD, _DWORD); weak
// int __fastcall device_destroy(_DWORD, _DWORD); weak
// int __fastcall cdev_init(_DWORD, _DWORD); weak
// int __fastcall cdev_del(_DWORD); weak
// int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *axi_fpga_dev_fops = &_this_module; // weak
_UNKNOWN _this_module; // weak
int axi_fpga_dev_num; // weak
int p_axi_fpga_dev; // weak
int base_vir_mem_addr; // weak
int base_vir_addr; // weak
int axi_fpga_class; // weak
// extern _UNKNOWN iomem_resource; weak
// extern _DWORD kmalloc_caches[7]; weak


//----- (00000000) --------------------------------------------------------
int axi_fpga_dev_open()
{
  return 0;
}

//----- (00000008) --------------------------------------------------------
int axi_fpga_dev_release()
{
  return 0;
}

//----- (00000010) --------------------------------------------------------
int __fastcall axi_fpga_dev_mmap(int a1, _DWORD *a2, int a3)
{
  unsigned int v3; // r2
  int v4; // r3
  int result; // r0

  v3 = a2[9] & 0xFFFFFFC3;
  v4 = a2[10] | 0x4044000;
  a2[9] = v3;
  a2[10] = v4;
  result = remap_pfn_range(a2, *a2, 0x40000, a2[1] - *a2, v3, a2, a3);
  if ( result )
  {
    printk("axi_fpga_dev_mmap error!\n");
    return -11;
  }
  return result;
}
// CC0: using guessed type int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// CDC: using guessed type int __fastcall printk(_DWORD);

//----- (00000068) --------------------------------------------------------
int __fastcall init_module(int a1, int a2)
{
  int v2; // r5
  const char *v3; // r0
  int v4; // r0
  const char *v5; // r0
  int v7; // r1
  int v8; // r1
  unsigned int v9; // r0

  printk("In axi fpga driver!\n");
  v2 = alloc_chrdev_region(&axi_fpga_dev_num, 0, 1, "axi_fpga_dev", a1, a2);
  if ( v2 < 0 )
  {
    v3 = "alloc axi_fpga_dev fail!\n";
LABEL_7:
    printk(v3);
    return v2;
  }
  v4 = kmem_cache_alloc(kmalloc_caches[6], 37748928);
  p_axi_fpga_dev = v4;
  if ( !v4 )
  {
    v5 = "kmalloc cdev fail!\n";
LABEL_10:
    printk(v5);
    return 1;
  }
  cdev_init(v4, &axi_fpga_dev_fops);
  *(_DWORD *)(p_axi_fpga_dev + 36) = &_this_module;
  v2 = cdev_add();
  if ( v2 )
  {
    v3 = "add axi_fpga_dev fail!\n";
    goto LABEL_7;
  }
  base_vir_mem_addr = _request_region(&iomem_resource, 0x40000000, 5120, "axi_fpga_vir_mem", 0);
  if ( !base_vir_mem_addr )
  {
    v5 = "request_mem_region failed!\n";
    goto LABEL_10;
  }
  printk("request_mem_region OK!\n");
  v7 = ioremap(0x40000000, 5120);
  base_vir_addr = v7;
  if ( !v7 )
  {
    printk("ioremap fail!\n");
    printk("!!!*base_vir_addr = 0x%x\n", base_vir_addr);
    return -1;
  }
  printk("AXI fpga dev virtual address is 0x%x\n", v7);
  v8 = *(_DWORD *)base_vir_addr;
  __dsb(0xFu);
  printk("*base_vir_addr = 0x%x\n", v8);
  v9 = _class_create(&_this_module, "axi_fpga_dev", &axi_fpga_class);
  axi_fpga_class = v9;
  if ( v9 > 0xFFFFF000 )
  {
    printk("Err:failed in creating axi fpga class.\n");
    return -1;
  }
  device_create(v9);
  return 0;
}
// 288: using guessed type void *axi_fpga_dev_fops;
// C98: using guessed type int axi_fpga_dev_num;
// C9C: using guessed type int p_axi_fpga_dev;
// CA0: using guessed type int base_vir_mem_addr;
// CA4: using guessed type int base_vir_addr;
// CA8: using guessed type int axi_fpga_class;
// CAC: using guessed type int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// CB0: using guessed type int __fastcall _class_create(_DWORD, _DWORD, _DWORD);
// CCC: using guessed type int __fastcall kmem_cache_alloc(_DWORD, _DWORD);
// CD0: using guessed type int cdev_add(void);
// CD4: using guessed type int __fastcall device_create(_DWORD);
// CD8: using guessed type int __fastcall ioremap(_DWORD, _DWORD);
// CDC: using guessed type int printk(const char *, ...);
// CF0: using guessed type int __fastcall cdev_init(_DWORD, _DWORD);
// CF4: using guessed type _DWORD kmalloc_caches[7];
// CFC: using guessed type int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00000220) --------------------------------------------------------
int cleanup_module()
{
  unregister_chrdev_region(axi_fpga_dev_num, 1);
  cdev_del(p_axi_fpga_dev);
  kfree(p_axi_fpga_dev);
  iounmap(base_vir_addr);
  _release_region(&iomem_resource, 0x40000000, 5120);
  device_destroy(axi_fpga_class, axi_fpga_dev_num);
  class_destroy(axi_fpga_class);
  return printk("Bye Bye axi fpga driver!\n");
}
// C98: using guessed type int axi_fpga_dev_num;
// C9C: using guessed type int p_axi_fpga_dev;
// CA4: using guessed type int base_vir_addr;
// CA8: using guessed type int axi_fpga_class;
// CB8: using guessed type int __fastcall class_destroy(_DWORD);
// CBC: using guessed type int __fastcall iounmap(_DWORD);
// CC4: using guessed type int __fastcall kfree(_DWORD);
// CC8: using guessed type int __fastcall _release_region(_DWORD, _DWORD, _DWORD);
// CDC: using guessed type int printk(const char *, ...);
// CE0: using guessed type int __fastcall unregister_chrdev_region(_DWORD, _DWORD);
// CE4: using guessed type int __fastcall device_destroy(_DWORD, _DWORD);
// CF8: using guessed type int __fastcall cdev_del(_DWORD);

// nfuncs=22 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
