/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int fpga_mem_open();
int fpga_mem_release();
int __fastcall fpga_mem_mmap(int, _DWORD *, int); // idb
int __fastcall init_module(int, int); // idb
int fpga_mem_exit(); // idb
// int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _class_create(_DWORD, _DWORD, _DWORD); weak
// int __fastcall class_destroy(_DWORD); weak
// int __fastcall iounmap(_DWORD); weak
// int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall kfree(_DWORD); weak
// int __fastcall _release_region(_DWORD, _DWORD, _DWORD); weak
// int __fastcall kmem_cache_alloc(_DWORD, _DWORD); weak
// int cdev_add(void); weak
// int __fastcall device_create(_DWORD); weak
// int __fastcall ioremap(_DWORD, _DWORD); weak
// int printk(const char *, ...); weak
// int __fastcall unregister_chrdev_region(_DWORD, _DWORD); weak
// int __fastcall device_destroy(_DWORD, _DWORD); weak
// int __fastcall cdev_init(_DWORD, _DWORD); weak
// int __fastcall cdev_del(_DWORD); weak
// int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

void *fpga_mem_fops = &_this_module; // weak
int fpga_mem_offset_addr = 251658240; // weak
_UNKNOWN _this_module; // weak
int fpga_mem_num; // weak
int p_fpga_mem; // weak
int base_vir_mem_addr; // weak
int base_vir_addr; // weak
int fpga_mem_class; // weak
// extern _UNKNOWN iomem_resource; weak
// extern _DWORD kmalloc_caches[7]; weak


//----- (00000000) --------------------------------------------------------
int fpga_mem_open()
{
  return 0;
}

//----- (00000008) --------------------------------------------------------
int fpga_mem_release()
{
  return 0;
}

//----- (00000010) --------------------------------------------------------
int __fastcall fpga_mem_mmap(int a1, _DWORD *a2, int a3)
{
  int v3; // r12
  int result; // r0

  v3 = a2[9];
  a2[10] |= 0x4044000u;
  v3 &= 0xFFFFFFC3;
  a2[9] = v3;
  result = remap_pfn_range(a2, *a2, fpga_mem_offset_addr >> 12, a2[1] - *a2, v3, a2, a3);
  if ( result )
  {
    printk("fpga_mem_mmap error!\n");
    return -9;
  }
  return result;
}
// 53C: using guessed type int fpga_mem_offset_addr;
// D00: using guessed type int __fastcall remap_pfn_range(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// D1C: using guessed type int __fastcall printk(_DWORD);

//----- (00000078) --------------------------------------------------------
int __fastcall init_module(int a1, int a2)
{
  int v2; // r5
  int v3; // r0
  int v5; // r1
  unsigned int v6; // r0

  printk("In fpga mem driver!\n");
  v2 = alloc_chrdev_region(&fpga_mem_num, 0, 1, "fpga_mem", a1, a2);
  if ( v2 >= 0 )
  {
    v3 = kmem_cache_alloc(kmalloc_caches[6], 37748928);
    p_fpga_mem = v3;
    if ( !v3 )
    {
      printk("kmalloc cdev fail!\n");
      return -10;
    }
    cdev_init(v3, &fpga_mem_fops);
    *(_DWORD *)(p_fpga_mem + 36) = &_this_module;
    v2 = cdev_add();
    if ( v2 )
    {
      printk("add fpga_mem fail!\n");
      return -11;
    }
    base_vir_mem_addr = _request_region(&iomem_resource, fpga_mem_offset_addr, 0x1000000, "fpga_vir_mem", 0);
    if ( !base_vir_mem_addr )
    {
      printk("request_mem_region failed!\n");
      return -12;
    }
    printk("request_mem_region OK!\n");
    v5 = ioremap(fpga_mem_offset_addr, 0x1000000);
    base_vir_addr = v5;
    if ( !v5 )
    {
      printk("ioremap fail!\n");
      printk("!!!*base_vir_addr = 0x%x\n", base_vir_addr);
      return -13;
    }
    printk("fpga mem virtual address is 0x%x\n", v5);
    v6 = _class_create(&_this_module, "fpga_mem", &fpga_mem_class);
    fpga_mem_class = v6;
    if ( v6 > 0xFFFFF000 )
    {
      printk("Err:failed in creating fpga mem class.\n");
      return -14;
    }
    device_create(v6);
  }
  else
  {
    printk("alloc fpga_mem fail!\n");
  }
  return v2;
}
// 2A0: using guessed type void *fpga_mem_fops;
// 53C: using guessed type int fpga_mem_offset_addr;
// CD8: using guessed type int fpga_mem_num;
// CDC: using guessed type int p_fpga_mem;
// CE0: using guessed type int base_vir_mem_addr;
// CE4: using guessed type int base_vir_addr;
// CE8: using guessed type int fpga_mem_class;
// CEC: using guessed type int __fastcall alloc_chrdev_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// CF0: using guessed type int __fastcall _class_create(_DWORD, _DWORD, _DWORD);
// D0C: using guessed type int __fastcall kmem_cache_alloc(_DWORD, _DWORD);
// D10: using guessed type int cdev_add(void);
// D14: using guessed type int __fastcall device_create(_DWORD);
// D18: using guessed type int __fastcall ioremap(_DWORD, _DWORD);
// D1C: using guessed type int printk(const char *, ...);
// D34: using guessed type int __fastcall cdev_init(_DWORD, _DWORD);
// D38: using guessed type _DWORD kmalloc_caches[7];
// D40: using guessed type int __fastcall _request_region(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00000230) --------------------------------------------------------
int fpga_mem_exit()
{
  unregister_chrdev_region(fpga_mem_num, 1);
  cdev_del(p_fpga_mem);
  kfree(p_fpga_mem);
  iounmap(base_vir_addr);
  _release_region(&iomem_resource, fpga_mem_offset_addr, 0x1000000);
  device_destroy(fpga_mem_class, fpga_mem_num);
  class_destroy(fpga_mem_class);
  return printk("Bye Bye fpga mem driver!\n");
}
// 53C: using guessed type int fpga_mem_offset_addr;
// CD8: using guessed type int fpga_mem_num;
// CDC: using guessed type int p_fpga_mem;
// CE4: using guessed type int base_vir_addr;
// CE8: using guessed type int fpga_mem_class;
// CF8: using guessed type int __fastcall class_destroy(_DWORD);
// CFC: using guessed type int __fastcall iounmap(_DWORD);
// D04: using guessed type int __fastcall kfree(_DWORD);
// D08: using guessed type int __fastcall _release_region(_DWORD, _DWORD, _DWORD);
// D1C: using guessed type int printk(const char *, ...);
// D20: using guessed type int __fastcall unregister_chrdev_region(_DWORD, _DWORD);
// D24: using guessed type int __fastcall device_destroy(_DWORD, _DWORD);
// D3C: using guessed type int __fastcall cdev_del(_DWORD);

// nfuncs=22 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
