
ASN1_GENERALIZEDTIME * d2i_ASN1_GENERALIZEDTIME(ASN1_GENERALIZEDTIME **a,uchar **in,long len)

{
  ASN1_GENERALIZEDTIME *pAVar1;
  
  pAVar1 = (ASN1_GENERALIZEDTIME *)ASN1_item_d2i((ASN1_VALUE **)a,in,len,DAT_000bbd10);
  return pAVar1;
}

