
ASN1_UNIVERSALSTRING * d2i_ASN1_UNIVERSALSTRING(ASN1_UNIVERSALSTRING **a,uchar **in,long len)

{
  ASN1_UNIVERSALSTRING *pAVar1;
  
  pAVar1 = (ASN1_UNIVERSALSTRING *)ASN1_item_d2i((ASN1_VALUE **)a,in,len,DAT_000bbd70);
  return pAVar1;
}

